# Define your mapping dictionary here.
# For example, tokens in the text "apple, banana, cherry" might be mapped to new values.
MAPPING = {
    "♂": "futanari",
    "female focus": "solo",
    "sharp claws": "sharp fingernails",
    "silver hair": "white hair",
    "bridget": "bridget (guilty gear)",
    "2b (nier automata)": "2b (nier:automata)",
    "extra balls": "extra testicles",
    "multi balls": "extra testicles",
    "multi penis": "extra penises",
    "horsecock": "horse penis",
    "equine penis": "horse penis",
    "muscular futanari": "muscular female",
    "picture": "cellphone photo",
    "cellphone_photo": "cellphone photo",
    "exposed penis": "penis out",
    "exposed shoulders": "bare shoulders",
    "exposed torso": "midriff",
    "huge thighs": "thick thighs",
    "mostly nude": "partially undressed",
    "solo futanari": "solo, futanari",
    "mostly nude futanari": "partially undressed, futanari",
    "functionally nude futanari": "partially undressed, futanari",
    "functionally nude": "partially undressed",
    "partially clothed": "partially undressed",
    "useless clothing": "partially undressed",
    "hidden penis": "covered penis",
    "light-skinned futanari": "pale skin, futanari",
    "fair skinned futanari": "pale skin, futanari",
    "pale futanari": "pale skin, futanari",
    "light skin": "pale skin",
    "looking pleasured": "aroused",
    "nipple bulge": "covered nipples",
    "nipple outline": "covered nipples",
    "nipples visible through clothing": "covered nipples",
    "peace sign": "v",
    "pleasured face": "aroused",
    "pleasure face": "aroused",
    "revealing outfit": "revealing clothes",
    "revealing": "revealing clothes",
    "smiling": "smile",
    "smiling at viewer": "smile, looking at viewer",
    "standing position": "standing",
    "staring at viewer": "staring",
    "teeth showing": "teeth",
    "teeth visible": "teeth",
    "text box": "english text",
    "tight clothing": "taut clothes",
    "vein": "veins",
    "smile at viewer": "smile",
    "hung futanari": "futanari, huge penis",
    "cleavage overflow": "bursting breasts",
    "penis ring": "cock ring",
    "areola bulge": "areola slip, puffy nipples, skindentation",
    "areolae visible through clothing": "areola slip",
    "athletic futanari": "futanari, athelete",
    "athletic futa": "futanari, athelete",
    "muscular legs": "muscular female, thick thighs",
    "public exposure": "public indecency",
    "pov eye contact": "looking at viewer",
    "exposed breasts": "breasts out",
    "faceless futanari": "futanari, head out of frame",
    "faceless futa": "futanari, head out of frame",
    "futa urethral insertion": "futanari, urethral insertion",
    "bottom heavy": "pear shaped figure",
    "choking": "asphyxiation",
    "completely naked": "completely nude",
    "completely nude female": "completely nude",
    "completely nude male": "completely nude",
    "erection in panties": "erection, penis in panties",
    "bubble butt": "huge ass",
    "athletic": "athlete",
    "beverage": "drink",
    "boner": "erection",
    "duo": "2girls",
    "ballkini": "covered testicles, bikini",
    "belly button": "navel",
    "veiny": "veins",
    "tight fit": "taut clothes",
    "testiclesack": "testicles",
    "dangling testicles": "sagging testicles",
    "hips": "wide hips",
    "low hanging testicles": "sagging testicles",
    "oversized testicles": "huge testicles",
    "partially retracted foreskin": "foreskin pull",
    "retracted foreskin": "foreskin pull",
    "uncut": "foreskin",
    "smooth penis": "huge penis",
    "breasts": "large breasts",
    "casual nudity": "nudist",
    "casual boner": "nudist, erection",
    "casual erection": "nudist, erection",
    "horny": "aroused",
    "casual exposure": "partially undressed",
    "intact": "foreskin",
    "voluptuous": "curvy",
    "penisgirl": "futanari",
    "dickgirl": "futanari",
    "intersex": "futanari",
    "futanari costume": "penis ornament",
    "small but hung": "small breasts, huge penis",
    "^ ^": "smile",
    "breasts bigger than head": "huge breasts",
    "breasts largeger than head": "huge breasts",
    "genitalwear": "penis ornament",
    "daytime": "day",
    "daylight": "sunlight",
    "handwear": "gloves",
    "curvaceous": "curvy",
    "curvy futa": "futanari, curvy",
    "penis sleeve (clothes)": "penis sleeve",
    "cock sheath": "penis sheath",
    "mostly clothed": "modest clothes",
    "freckles on breasts": "body freckles",
    "freckles on shoulders": "body freckles",
    "venus body": "curvy",
    "ai generated": "ai-generated",
    "ball bulge": "covered testicles",
    "breasts touching": "breast on breast",
    "cum on upper body": "cum on body",
    "cum on lower body": "cum on body",
    "pointed ears": "pointy ears",
    "huge butt": "huge ass",
    "multi arm": "extra arms",
    "multi genitalia": "extra penises",
    "multi limb": "extra arms",
    "muscular intersex": "muscular female, futanari",
    "animal genitalia on humanoid": "animal penis",
    "animal genitalia": "animal penis",
    "cum on ground": "cum pool",
    "horsepenis on humanoid": "horse penis",
    "horsecock on humanoid": "horse penis",
    "legs held open": "spread legs",
    "low-angle view": "from below",
    "one side up": "side ponytail",
    "testicles to knees": "gigantic testicles",
    "hiding erection": "covering crotch",
    "humanoid penis": "penis",
    "nude futanari": "futanari, nude",
    "uncircumcised": "foreskin",
    "1girls": "1girl",
    "ineffective clothing": "partially undressed",
    "testicles in panties": "covered testicles, panties",
    "testicles in underwear": "covered testicles, panties",
    "testicles past knees": "gigantic testicles, sagging testicles",
    "balls past knees": "gigantic testicles, sagging testicles",
    "muscles": "muscular",
    "precum trail": "precum string",
    "outside": "outdoors",
    "horseballs": "horse penis, testicles",
    "horsetesticles": "horse penis, testicles",
    "centauress": "centaur",
    "equid taur": "centaur",
    "horsecock futanari": "horse penis, futanari",
    "horsepenis futanari": "horse penis, futanari",
    "human with horsecock": "horse penis, futanari",
    "human with horsepenis": "horse penis, futanari",
    "human with animal genitalia": "horse penis, futanari",
    "dark-skinned futanari": "futanari, dark skin",
    "multi breast": "extra breasts",
    "multi head": "multiple heads",
    "polymastia": "extra breasts",
    "backsack": "tucked penis",
    "dicknipples": "penis nipples",
    "penisnipples": "penis nipples",
    "dick nipples": "penis nipples",
    "4 testicles": "4testes",
    "testicle bulge": "covered testicles",
    "polyphallia": "extra penises",
    "unretracted foreskin": "phimosis",
    "voluptuous female": "curvy",
    "autoimpregnation": "impregnation",
    "self impregnation": "impregnation",
    "trying not to cum": "orgasm denial",
    "teacher and student": "teacher, student",
    "giant testicles": "gigantic testicles",
    "shark futanari": "futanari, shark",
    "shark humanoid": "shark",
    "hung": "huge penis",
    "fit": "muscular female",
    "fit futanari": "muscular female, futanari",
    "futanari vampire": "futanari, vampire",
    "wii fit": "wii fit trainer",
    "penis bigger than body": "gigantic penis",
    "penis largeger than body": "gigantic penis",
    "thick foreskin": "foreskin",
    "bumpy foreskin": "foreskin, spiked penis",
    "large clitoris": "huge clitoris",
    "thick cum": "excessive cum",
    "penis and ball torture": "testicle torture",
    "covered erect nipples": "covered nipples, erect nipples",
    "testicles outline": "covered testicles",
    "muscular humanoid": "muscular female",
    "muscular gynomorph": "muscular female",
    "gynomorph": "female",
    "tan-skinned futanari": "futanari, tan",
    "hung bottom": "huge penis",
    "thick ass": "huge ass, thick thighs",
    "thick penis": "girthy penis",
    "ahe gao": "ahegao",
    "multi-penis": "extra penises",
    "long foreskin": "foreskin, phimosis",
    "hi res": "highres",
    "high resolution": "highres",
    "demon futanari": "futanari, demon",
    "demon futa": "futanari, demon",
    "hands-free": "handsfree ejaculation",
    "toned futa": "futanari, muscular female",
    "cumshot": "projectile cum",
    "multiple testicles": "extra testicles",
    "multiple balls": "extra testicles",
    "absurd res": "absurdres",
    "absurd resolution": "absurdres",
    "fully retracted foreskin": "foreskin pull",
    "multi nipple": "extra nipples",
    "urethral bulge": "bulging penis",
    "urethra bulge": "bulging penis",
    "large thighs": "thick thighs",
    "sweating": "sweat", 
    "sweaty": "sweat", 
    "sweaty body": "sweat", 
    "sweaty breasts": "sweat, huge breasts", 
    "sweaty genitalia": "sweat, huge penis", 
    "sweaty testicles": "sweat, huge testicles", 
    "scathach (final fantasy)": "scathach (ff14)",
    "erect penis": "erection",
    "testicles largeger than penis": "gigantic testicles",
    "testicles bigger than penis": "gigantic testicles",
    "balls bigger than penis": "gigantic testicles",
    "triple penis": "triphallia",
    "triphallism": "triphallia",
    "hermaphrodite": "futanari",
    "diphallism": "diphallia, extra penises",
    "diphallia": "diphallia, extra penises",
    "blush lines": "blush",
    "speech bubbles": "speech bubble",
    "sitting on chair": "sitting, on chair",
    "exposed nipples": "nipples",
    "hung futa": "futanari, huge penis",
    "large ass": "huge ass",
    "herm": "futanari",
    "getting erect": "half-erect",
    "chubby futanari": "futanari, chubby",
    "giant breasts": "gigantic breasts",
    "giant penis": "gigantic penis",
    "lactating": "lactation",
    "lactating nipples": "lactation, nipples",
    "locking back": "looking back",
    "chubby": "plump",
    "curvy figure": "curvy",
    "venus": "curvy",
    "venus futa": "curvy, futanari",
    "super mario bros.": "mario (series)",
    "stretched foreskin": "foreskin pull",
    "stretching foreskin": "foreskin pull",
    "sucking foreskin": "fellatio",
    "saggy testicles": "sagging testicles",
    "pregnant futa": "pregnant, futanari",
    "penisgirl": "futanari",
    "penisgirl female": "futanari",
    "penis bulge": "bulging penis",
    "mature futa": "mature female, futanari",
    "low hanging testicles": "sagging testicles",
    "large thighs": "thick thighs",
    "large butt": "huge ass",
    "large belly": "plump",
    "inner foreskin": "foreskin",
    "imminent orgasm": "bulging penis",
    "huge areola": "large areola",
    "high-angle view": "from above",
    "green eyess": "green eyes",
    "garter": "legwear garter",
    "futa solo": "1futa",
    "futa penis": "futanari",
    "futa is bigger": "futanari, penis size difference",
    "futa is largeger": "futanari, penis size difference",
    "foreskin folds": "foreskin",
    "penis clothing": "cock sock",
    "fat penis": "girthy penis",
    "fat ass": "huge ass",
    "exposed": "partially undressed",
    "dripping cum": "cumdrip",
    "dripping precum": "precum drip",
    "dripping penis": "cumdrip",
    "dripping wet": "wet",
    "curvy ass": "curvy",
    "curvy hips": "curvy",
    "curvy thighs": "curvy",
    "cum in own mouth": "drinking own cum, cum in mouth",
    "condom filling": "used condom on penis, excessive cum, ejaculation",
    "comparing": "size difference",
    "comparing penis": "penis size difference",
    "comparison": "size difference",
    "penis size comparison": "penis size difference",
    "chubby female": "plump",
    "censored genitalia": "censored",
    "censored penis": "censored",
    "censored pussy": "censored",
    "displaced genitalia": "misplaced genitals",
    "cameltail": "covered penis",
    "busty": "huge breasts",
    "bottomless skirt": "skirt, no panties",
    "boobjob": "paizuri",
    "ball grab": "testicle grab",
    "ball fondling": "caressing testicles",
    "back view": "from behind",
    "1penisgirl": "1futa",
    "1dickgirl": "1futa",
    "1female": "1girl",
    "voluptuous futanari": "curvy, futanari",
    "titjob": "paizuri",
    "throbbing testicles": "motion lines, twitching, bouncing testicles",
    "twitch lines": "motion lines, twitching",
    "thick hips": "wide hips",
    "thick": "curvy",
    "swollen testicles": "huge testicles",
    "stockings": "thighhighs",
    "steamy cum": "cum, steam",
    "sperm in mouth": "cum in mouth",
    "skimpy clothes": "revealing clothes",
    "skimpy bikini": "micro bikini",
    "skimpy": "revealing clothes",
    "pussy juice drip": "pussy juice trail",
    "backed up cum": "huge testicles, twitching, precum drip",
    "sperm": "sperm cell",
    "sweaty butt": "sweat, ass",
    "squeezing breasts": "breasts squeezed together",
    "throbbing penis": "twitching penis",
    "throbbing": "twitching penis",
    "thick nipples": "huge nipples",
    "spread butt": "spread anus",
    "tiny penis": "small penis",
    "teabagging": "testicles on face",
    "tea bagging": "testicles on face",
    "testicles on head": "testicles on face",
    "bbw": "fat",
    "huge hips": "wide hips",
    "purple haired futa": "purple hair, futanari",
    "nude futa": "nude, futanari",
    "naked": "nude",
    "wide ass": "huge ass, wide hips",
    "vagina": "pussy",
    "artificial pussy": "artificial vagina",
    "self sucking": "autofellatio",
    "erect nipples": "nipples",
    "wet pussy": "pussy, pussy juice",
    "vaginal penetration": "vaginal",
    "thick legs": "thick thighs",
    "thick butt": "huge ass",
    "testicles largeger than head": "gigantic testicles",
    "testicles bigger than head": "gigantic testicles",
    "tail penis": "penis tail",
    "sweaty": "sweat",
    "slightly chubby": "curvy",
    "self suck": "autofellatio",
    "presenting anus": "spread anus",
    "presenting butt": "spread anus",
    "obese futanari": "fat, futanari",
    "multi wing": "multiple wings",
    "mother": "motherly",
    "moaning in pleasure": "moaning",
    "milk squirt": "projectile lactation",
    "massive penis": "huge penis",
    "lying down": "lying",
    "legwear only": "legwear",
    "leaking milk": "lactation",
    "leaking": "dripping",
    "leaking cum": "precum drip",
    "large testicles small penis": "large testicles, small penis",
    "large nipples": "huge nipples",
    "lactate": "lactation",
    "sweaty legs": "sweat, thick thighs",
    "censor bar": "bar censor",
    "oppai": "huge breasts",
    "gradient background": "simple background",
    "night dress": "nightgown",
    "aya (thon2hk)": "aya shobon",
    "multi tail": "extra tails",
    "masturbating": "masturbation", 
    "extra penis": "extra penises",
    "closeup": "close-up",
    "triphalia": "triphallia",
    "dog penis": "canine penis",
    "twin tails": "twintails",
    "thighhigh boots": "thigh boots",
    "thigh high boots": "thigh boots",
    "puffy inverted nipples": "puffy nipples, inverted nipples",
    "dog penis": "canine penis",
    "legs spread": "spread legs",
    "erect": "erection",
    "futa only": "solo, futanari",
    "transgender": "futanari",
    "tall": "tall female",
    "front view": "straight-on",
    "penis outline": "covered penis",
    "blonde hair futa": "futanari, blonde hair",
    "blonde futa": "futanari, blonde hair",
    "erection under clothing": "erection under clothes",
    "medium skirt": "skirt",
    "cropped shirt": "crop top",
    "mommy": "motherly",
    "see-through clothing": "see-through clothes",
    "freckles on face": "freckles",
    "thigh slit": "side slit",
    "cellphone": "phone",
    "smartphone": "phone",
    "futanari transformation": "futanari",
    "penis-tail": "tucked penis",
    "penis largeger than torso": "gigantic penis",
    "penis bigger than torso": "gigantic penis",
    "corridor": "hallway",
    "full body": "wide shot",
    "penis to the knee": "penis to the knees",
    "semi-erect": "half-erect",
    "bending over": "bent over",
    "bending forward": "leaning forward",
    "english text": "text",
    "captions": "text",
    "areola": "areolae",
    "flaccid penis": "flaccid",
    "solo futa": "futanari, solo",
    "translucent clothing": "see-through clothes",
    "hyper penis":"gigantic penis",
    "digital media (artwork)": "digital illustration",
    "friendship is magic": "my little pony: friendship is magic",
    "furry with non-furry": "interspecies",
    "muscular": "muscular female",
    "solo female": "solo, 1girl",
    "blonde female": "blonde hair, female",
    "breast support": "breast hold",
    "yellow topwear": "yellow shirt",
    "milk maid": "milkmaid",
    "milkmaid (profession)": "milkmaid",
    "breast squish": "breasts squeezed together",
    "breasts together": "breasts squeezed together",
    "penis largeger than ass": "huge penis",
    "penis largeger than head": "huge penis",
    "penis bigger than ass": "huge penis",
    "penis bigger than head": "huge penis",
    "pawg": "huge ass",
    "not loving pregnancy": "pregnant, angry",
    "lots of jewelry": "jewelry",
    "lacatation without expression": "expression",
    "incest pregnancy": "incest, pregnant",
    "inbreeding": "incest",
    "inbred bastard": "incest, pregnant",
    "human on anthro": "interspecies",
    "huge bulge": "stomach bulge",
    "hyper bulge": "stomach bulge",
    "testicles largeger than breasts": "huge testicles",
    "testicles bigger than breasts": "huge testicles",
    "ball clench": "testicles clench",
    "ball clenching": "testicles clench",
    "testicle clench": "testicles clench",
    "testicles clenching": "testicles clench",
    "tattoo on breast": "breast tattoo",
    "tattoo on breasts": "breast tattoo",
    "tattoo on leg": "leg tattoo",
    "tattoo on legs": "leg tattoo",
    "sunglasses on head": "sunglasses, eyewear on head",
    "stomach deformation": "stomach bulge",
    "soft breasts": "sagging breasts",
    "shorter male": "smaller male",
    "romantic couple": "couple, dating",
    "pussy juice string": "pussy juice string",
    "pregnancy": "pregnant",
    "pupilless eyes": "blank eyes",
    "bodily fluids": "cum, sweat",
    "female": "1girl",
    "gigantic ass": "huge ass",
    "mouse humanoid": "mouse ears, mouse tail",
    "male": "1boy",
    "anthro": "animal ears",
    "face markings": "facial mark",
    "female only": "solo",
    "long nails": "long fingernails",
    "gold jewelry": "gold necklace, gold earrings, gold bracelet",
    "gold eyeshadow": "yellow eyeshadow",
    "horn": "single horn",
    "raceplay": "interracial",
    "grabbing boob": "grabbing single breast",
    "areolae": "large areolae",
    "straight": "hetero",
    "gluteal fold": "underbutt",
    "duo focus": "couple",
    "eyewear": "eyewear on head",
    "genital fluids": "precum",
    "black lipstick": "black lips",
    "hand on testicles": "testicle grab",
    "male female": "hetero",
    "trio": "threesome",
    "hooved fingers": "hooves",
    "hooved toes": "hooves",
    "pink nipples": "nipples",
    "pink areola": "large areolae",
    "white body": "pale skin",
    "beauty mark": "mole",
    "bulging breasts": "bursting breasts",
    "happy female": "happy, 1girl",
    "clothed female": "modest clothes",
    "holding object": "holding",
    "hourglass figure": "hourglass",
    "mature": "mature female",
    "farmgirl": "farmer, 1girl",
    "gigantic cum inflation": "cum inflation, big belly",
    "gigantic belly": "big belly",
    "cum leaking": "cum overflow",
    "cum inside": "internal cumshot",
    "splits": "split",
    "video games": "video game",
    "brown body": "tan",
    "headwear": "hat",
    "exposed pussy": "pussy",
    "cum explosion": "projectile ejaculation, excessive cum",
    "gigantic hips": "wide hips",
    "gigantic nipples": "huge nipples",
    "gigantic thighs": "thick thighs",
    "curvy female": "curvy",
    "outdoor sex": "public indecency, outdoors, sex",
    "hand on knee": "hand on own knee",
    "head thrown back": "head back",
    "pokemon (species)": "pokemon (creature)",
    "puffy areolae": "puffy nipples, inverted nipples, large areolae",
    "puffy areola": "puffy nipples, inverted nipples, large areolae",
    "straight sex": "hetero, sex",
    "tremble lines": "trembling",
    "voyeur": "voyeurism",
    "fully clothed": "modest clothes",
    "large areola": "large areolae",
    "huge areola": "large areolae",
    "huge areolae": "large areolae",
    "top heavy": "gigantic breasts",
    "grabbing leg": "grabbing own thigh",
    "holding legs up": "holding legs",
    "light-skinned female": "pale skin",
    "crystals": "crystal", 
    "ready to pop": "pregnant, big belly",
    "lactation without expressing": "lactation",
    "purple clothing": "purple clothes",
    "startled": "surprised",
    "cumming from fetal movement": "fetal movement, orgasm",
    "black nail polish": "black nails, nail polish",
    "barbed penis": "spiked penis",
    "being watched": "voyeurism",
    "excessive precum": "precum, excessive cum",
    "nun's habit": "habit",
    "multiple females": "multiple girls",
    "penis worship": "licking penis, penis on face, penis awe",
    "younger male": "smaller male",
    "small dom large sub": "small dom big sub",
    "light-skinned male": "pale skin, 1boy",
    "brazilian": "tan",
    "doggy style": "doggystyle",
    "female penetrated": "vaginal",
    "femboy": "otoko no ko",
    "hung trap": "otoko no ko, huge penis",
    "internal": "internal cumshot",
    "looking at partner": "looking at another",
    "older female": "larger female",
    "trap": "otoko no ko",
    "penetration": "sex",
    "male penetrating": "sex, hetero",
    "breast grab": "grabbing another's breast",
    "creamy cum": "cum, slime (substance)",
    "cumming": "orgasm",
    "light-skinned futa": "pale skin, futanari",
    "smooth testicles": "testicles",
    "testicles clench": "ejaculation, orgasm, cum",
    "blue nail polish": "blue nails, nail polish",
    "thin waist": "narrow waist",
    "taller girl": "larger female",
    "taller female": "larger female",
    "precum through underwear": "precum through clothes",
    "short skirt": "miniskirt",
    "digital drawing (artwork)": "digital illustration",
    "pom poms": "pom pom (cheerleading)",
    "athlete": "toned",
    "athletic female": "toned female",
    "fit female": "toned female",
    "femboy": "otoko no ko",
    "femboy on female": "hetero",
    "girly": "bishounen",
    "hand on hip": "hand on own hip",
    "winking": "one eye closed",
    "wink": "one eye closed",
    "wrecked ass": "extreme gaping, after anal",
    "ruined ass": "extreme gaping, after anal",
    "ruined anus": "extreme gaping, after anal",
    "destroyed anus": "extreme gaping, after anal",
    "destroyed ass": "extreme gaping, after anal",
    "gaping anus": "gaping, after anal",
    "gigantic gape": "extreme gaping",
    "female female": "yuri",
    "breasts on floor": "breast rest, gigantic breasts",
    "legwear": "thighhighs",
    "equid": "horse ears",
    "equine": "horse ears",
    "huge belly": "big belly",
    "laying on side": "lying, on side",
    "laying": "lying",
    "pockets visible": "exposed pocket",
    "exposed pockets": "exposed pocket",
    "long breasts": "sagging breasts",
    "gritted teeth": "clenched teeth",
    "cum inflation belly": "cum inflation, big belly",
    "blue sneakers": "sneakers, blue shoes",
    "hand on ass": "hand on another's ass",
    "bikini bottom, bikini top": "bikini",
    "purple clothes": "purple sweater",
    "navel line": "pregnant, big belly",
    "untied shoes": "untied shoelaces",
    "endured face": "clenched teeth",
    "playful": "happy",
    "pussy juice string": "pussy juice trail",
    "black and white hair": "streaked hair, white hair",
    "pulling hair": "grabbing another's hair",
    "hair pull": "grabbing another's hair",
    "multiple arms": "extra arms",
    "balloons": "balloon",
    "sneaker": "sneakers",
    "wet skin": "wet",
    "big breasts": "large breasts",
    "big penis": "large penis",
    "big testicles": "large testicles",
    "big ass": "huge ass",
    "baggy clothing": "baggy clothes",
    "big butt": "huge ass",
    "butt": "ass",
    "belly bulge": "stomach bulge",
    "big nipples": "huge nipples",
    "long penis": "huge penis",
    "steamy breath": "heavy breathing",
    "cum everywhere": "excessive cum",
    "projectile ejaculation": "projectile cum",
    "big areolae": "large areolae",
    "gigantic penetration": "gigantic penis, sex",
    "gigantic butt": "huge ass",
    "gigantic stomach bulge": "stomach bulge, big belly",
    "ripped clothing": "torn clothes",
    "imminent sex": "imminent penetration",
    "thigh highs": "thighhighs",
    "bigger female": "larger female",
    "gigantic cum": "cum inflation, big belly, excessive cum",
    "gigantic inflation": "cum inflation, big belly, excessive cum",
    "scotum": "testicles",
    "swinging testicles": "sagging testicles, bouncing testicles",
    "big bulge": "stomach bulge, big belly",
    "vaginal sex": "vaginal",
    "tan skin": "tan",
    "anal sex": "anal",
    "side view": "from side",
    "1boy1girl": "1boy, 1girl",
    "absurdly large penis": "gigantic penis",
    "pregnant female": "pregnant",
    "from behind position": "from behind",
    "hanging testicles": "sagging testicles",
    "mixed bathing": "mixed-sex bathing",
    "penis in thighhighs": "penis in thighhigh",
    "penis in stocking": "penis in thighhigh",
    "big thighs": "thick thighs",
    "bulge through clothing": "bulge",
    "erection under skirt": "erection under clothes, skirt",
    "penis under clothes": "erection under clothes",
    "big hips": "wide hips",
    "blushing": "blush",
    "english dialogue": "speech bubble",
    "fat thighs": "thick thighs",
    "futa giantess": "tall female, futanari",
    "futa vampire": "vampire, futanari",
    "hairless testicles": "smooth testicles",
    "heels": "high heels",
    "leaking penis": "precum drip",
    "leaking precum": "precum drip",
    "macro futa": "futanari, tall female",
    "pale female": "pale skin",
    "pale futa": "futanari, pale skin",
    "penis under dress": "dress, erection under clothes",
    "thick testicles": "huge testicles",
    "bulge under clothes": "bulge",
    "pubes": "pubic hair",
    "precum through clothing": "precum through clothes",
    "penis tuck": "tucked penis",
    "penis in sock": "cock sock",
    "muscular futa": "muscular female, futanari",
    "medial ring": "horse penis",
    "maid dress": "maid apron",
    "maid outfit": "maid apron",
    "full-package futa": "full-package futanari",
    "full-package futanarinarinari": "full-package futanari",
    "fishnet legwear": "fishnet thighhighs",
    "erect nipples under clothes": "covered nipples",
    "giant futa": "tall female, futanari",
    "talking to viewer": "looking at viewer",
    "thunder thighs": "thick thighs",
    "penis under skirt": "erection under clothes, skirt",
    "penis to the knees": "huge penis, half-erect",
    "city background": "city",
    "tucking": "tucked penis",
    "blender": "blender (medium)",
    "blender (software)": "blender (medium)",
    "blender eevee": "blender (medium)",
    "sock": "socks",
    "2futas": "futanari, 2girls",
    "futa focus": "futanari, solo",
    "voluptuous futa": "futanari, curvy",
    "multicolored body": "colored skin",
    "penissleeve": "penis sleeve",
    "penis sleeve": "cock sock",
    "very long penis": "huge penis",
    "breasts bigger than torso": "gigantic breasts",
    "muscular thighs": "thick thighs, muscular female",
    "2futas": "futanari, 2girls",
    "3futas": "futanari, 3girls",
    "4futas": "futanari, 4girls",
    "5futas": "futanari, 5girls",
    "6futas": "futanari, 6girls",
    "hairy armpits": "armpit hair",
    "penis longer than knee": "gigantic penis",
    "gigantic tits": "gigantic breasts",
    "huge tits": "huge breasts",
    "large tits": "large breasts",
    "multiple futa": "multiple girls, futanari",
    "nude female": "nude",
    "throat fuck": "deepthroat",
    "text bubble": "speech bubble",
    "dialogue bubble": "speech bubble",
    "emotionless": "expressionless",
    "married couple": "couple",
    "married": "couple",
    "penis sock": "cock sock",
    "skintight clothing": "tight clothes",
    "skintight clothes": "tight clothes",
    "blowjob": "fellatio",
    "schoolgirl": "school uniform",
    "cum through clothing": "cum through clothes",
    "cum in clothing": "cum in clothes",
    "cum on own hand": "cum on fingers",
    "cum on hand": "cum on fingers",
    "cum in sock": "cum in clothes, cock sock",
    "group": "multiple girls",
    "futa on futa": "futa with futa",
    "male only": "1boy, solo",
    "plump lips": "lips",
    "lifted shirt": "shirt, clothes lift",
    "clothing lift": "clothes lift",
    "equine genitalia": "horse penis",
    "filled condom": "used condom",
    "areolae slip": "areola slip",
    "gigantic areolae": "large areolae",
    "gigantic areola": "large areolae",
    "futa armpit hair": "futanari, armpit hair",
    "fishnet": "fishnets",
    "3d (artwork)": "3d",
    "tired": "exhausted",
    "penile masturbation": "futanari masturbation",
    "hard on": "erection",
    "hard-on": "erection",
    "thigh squish": "thick thighs, skindentation",
    "black penis": "dark penis",
    "open clothing": "open clothes",
    "dark-skinned futa": "futanari, dark skin",
    "dark-skinned futanari": "futanari, dark skin",
    "tanned-skinned futa": "futanari, tan",
    "tanned-skinned futanari": "futanari, tan",
    "nude male": 'nude',
    "flashing breasts": "breasts out, nipples",
    "curvy body": "curvy",
    "testicles under clothes": "covered testicles",
    "feminine male": "otoko no ko",
    "big areola": "large areolae",
    "big areolae": "large areolae",
    "large areola": "large areolae",
    "ass bigger than head": "huge ass",
    "long gloves": "elbow gloves",
    "5 sock outfit": "socks, cock sock",
    "hanging penis": "half-erect",
    "dangling penis": "half-erect",
    "fucked from behind": "sex from behind",
    "fucked senseless": "fucked silly",
    "fucked into submission": "fucked silly",
    "trans woman": "futanari",
    "wife": "housewife",
    "thighhigh socks": "thighhighs",
    "thighhigh thighhighs": "thighhighs",
    "thigh high thighhighs": "thighhighs",
    "thigh high socks": "thighhighs",
    "tanned skin": "tan",
    "tall futa": "futanari, tall female",
    "taller futa": "futanari, tall female",
    "naked futa": "futanari, nude",
    "holidays": "vacation",
    "cum drip": "cumdrip",
    "penis warmer": "cock sock",
    "orgasm face": "orgasm",
    "skintight": "skin tight",
    "long socks": "tube socks",

    # Style variations
    "open clothing": "open clothes",
    "torn clothes": "torn clothes",
    "ripped clothing": "torn clothes",
    "tight clothing": "tight clothes",
    "loose clothing": "loose clothes",
    "skimpy clothing": "skimpy clothes",
    "slutty clothing": "skimpy clothes",
    "revealing clothing": "revealing clothes",
    "minimal clothing": "revealing clothes",
    "baggy clothing": "loose clothes",

    # Color-based
    "black clothing": "black clothes",
    "white clothing": "white clothes",
    "red clothing": "red clothes",
    "blue clothing": "blue clothes",
    "green clothing": "green clothes",
    "yellow clothing": "yellow clothes",
    "purple clothing": "purple clothes",
    "pink clothing": "pink clothes",
    "orange clothing": "orange clothes",
    "gray clothing": "gray clothes",
    "grey clothing": "gray clothes",

    # Pattern-based
    "striped clothing": "striped clothes",
    "polka dot clothing": "polka dot clothes",
    "plaid clothing": "plaid clothes",
    "checkered clothing": "checkered clothes",
    "camouflage clothing": "camouflage clothes",
    "animal print clothing": "animal print clothes",
    "leopard print clothing": "leopard print clothes",
    "zebra print clothing": "zebra print clothes",

    # Material/fabric
    "leather clothing": "leather clothes",
    "latex clothing": "latex clothes",
    "silk clothing": "silk clothes",
    "cotton clothing": "cotton clothes",
    "denim clothing": "denim clothes",
    "lace clothing": "lace clothes",

    # Style categories
    "military clothing": "military clothes",
    "school uniform clothing": "school uniform clothes",
    "maid clothing": "maid clothes",
    "casual clothing": "casual clothes",
    "formal clothing": "formal clothes",
    "winter clothing": "winter clothes",
    "summer clothing": "summer clothes",
    "swimwear clothing": "swimwear clothes",
    "business clothing": "business clothes",
    "sport clothing": "sport clothes",
}

COMBO_MAPPING = {
    ("tall female","narrow waist", "wide hips", "sagging breasts", "thick thighs","mature female", "hip bones"): "milf",
    ("knotted penis", "canine penis", "red penis", "knot", "pointed tip penis"): "canine penis, knotted penis",
    ("mature female", "milf", "aged up", "sagging breasts", "wide hips", "narrow waist"): "milf",
    ("mature female", "milf", "sagging breasts", "wide hips", "narrow waist"): "milf",
    ("thighs", "thick thighs"): "thick thighs",
    ("ass", "huge ass"): "huge ass",
}

PARTIAL_MAPPING = {
    " (mlp)": "",
    "massive": "gigantic",
    "enormous": "gigantic",
    "cumflation": "cum inflation",
    "cumflated": "cum inflation",
    "hyper": "gigantic",
    "balls": "testicles",
    "horsecock": "horse penis",
    "cock": "penis",
    "dick": "penis",
    "penis ring": "cock ring",
    "gynomorph": "female",
    "pale-skinned": "pale",
    "violet ": "purple ",
    "stockings": "thighhighs",
    "amlargeuous": "ambiguous",
    "nier automata": "nier:automata",
}

PARTIAL_EXCEPTIONS = {
    "cock": {"cock ring", "cock sock"},
}

# Remove mapping: tokens that exactly match any key in this set will be removed.
REMOVE_MAPPING = {
    "5 fingers",
    "uncensored penis",
    "circumcised",
    "clothed breasts",
    "more at source",
    "background",
    "o",
    "eyebrows",
    "maximum strike edit",
    "idian",
    "alternate body type",
    "higher resolution available",
    "eyebrows visible through hair",
    "gigantic genitalia",
    "hyper genitalia",
    "genitals",
    "fingers",
    "helpless",
    "10s",
    "poorly edited",
    "hair",
    "2020s",
    "hyper genetalia",
    "mammal",
    "bad twitter id",
    "variant set",
    "colorized",
    "copyright name",
    "english commentary",
    "stable diffusion",
    "borrowed character",
    "pony diffusion xl",
    "closed mouth",
    "high resolution duplicate",
    "breast expansion",
    "dialogue",
    "alternate costume",
    "twitter username",
    "alternate breast size",
    "size fetish",
    "balls expansion",
    "testicles expansion",
    "public",
    "seductive",
    "highres",
    "ai-generated",
    "absurdres",
    "detailed",
    "chiaroscuro",
    "ornate",
    "ornate clothes",
    "light particles",
    "action shot",
    "shadows",
    "1futa",
    "aged up",
    "gigantic",
    "decensored",
    "redraw",
    "commentary request",
    "colored",
    "color edit",
    "english",
    "3rd party edit",
    "color",
    "chest",
    "third-party edit",
    "legs",
    "hard translated",
    "xtraTestesRow",
    "human only",
    "penis",
    "testicles",
    "breasts",
    "commissioner upload",
    "2d",
    "2d (artwork)",
    "2d artwork",
    "removable censorship",
    "translated",
    "pornography",
    "virtual youtuber",
    "bin artbin",
    "image sample",
    "pixiv sample",
    "story",
    "story in description",
    "excessive flesh",
    "breasticles",
    "alternate version available",
    "alternate version at source",
    "source request",
    "milestone celebration",
    "samsung",
    "samsung galaxy",
    "tumblr",
    "human",
    "humanoid",
    "original",
    "original character",
    "original characters",
    "pose",
    "posing",
    "clothed",
    "clothes",
    "clothing",
    "footwear",
    "shaved crotch",
    "uncensored",
    "photoshop",
    "artist upload",
    "has uncensored version",
    "second-party source",
    "third-party source",
    "duplicate",
    "bad id",
    "bad pixiv id",
    "bad tumblr id",
    "civitai",
    "video game character", 
    "video game franchise", 
    "commission",
    "commission art",
    "humanoid genitalia",
    "self upload",
    "artist request",
    "tagme",
    "what",
    "translation request",
    "two tone hair",
    "nai diffusion",
    "hourglass expansion",
    "edit",
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014",
    "2013",
    "2012",
    "2011",
    "2010"
}